kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 6443
    hostPort: 39209  # 保持你的固化端口
    protocol: TCP
- role: worker        # 新增的工作节点
